name: Deploy

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to CocoaPods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        set -eo pipefail
        export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` | gawk 'match($0, /v(.+)/, o) { print o[1] }')
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
