name: Deploy

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      name: Create GitHub Release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to CocoaPods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        set -eo pipefail
        export LIB_VERSION=${GITHUB_REF/refs\/tags\/v/}
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
