name: Linux
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift: ['5.1']
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Swiftenv
      run: git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
    - name: Install Swift
      run: ~/.swiftenv/bin/swiftenv install ${{ matrix.swift }}
    - name: Build
      run: ~/.swiftenv/shims/swift build
    - name: Test
      run: ~/.swiftenv/shims/swift test
